# Generated by Django 3.2.6 on 2022-04-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recipe',
            new_name='recipes',
        ),
    ]
