# Generated by Django 3.2.6 on 2022-04-07 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_recipe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('friday_breakfast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday_breakfast', to='menu.recipe')),
                ('friday_dinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday_dinner', to='menu.recipe')),
                ('friday_lunch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday_lunch', to='menu.recipe')),
                ('monday_breakfast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday_breakfast', to='menu.recipe')),
                ('monday_dinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday_dinner', to='menu.recipe')),
                ('monday_lunch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday_lunch', to='menu.recipe')),
                ('saturday_breakfast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_breakfast', to='menu.recipe')),
                ('saturday_dinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_dinner', to='menu.recipe')),
                ('saturday_lunch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_lunch', to='menu.recipe')),
                ('sunday_breakfast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_breakfast', to='menu.recipe')),
                ('sunday_dinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_dinner', to='menu.recipe')),
                ('sunday_lunch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_lunch', to='menu.recipe')),
                ('thursday_breakfast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_breakfast', to='menu.recipe')),
                ('thursday_dinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_dinner', to='menu.recipe')),
                ('thursday_lunch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_lunch', to='menu.recipe')),
                ('tuesday_breakfast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_breakfast', to='menu.recipe')),
                ('tuesday_dinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_dinner', to='menu.recipe')),
                ('tuesday_lunch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_lunch', to='menu.recipe')),
                ('wednesday_breakfast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_breakfast', to='menu.recipe')),
                ('wednesday_dinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_dinner', to='menu.recipe')),
                ('wednesday_lunch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_lunch', to='menu.recipe')),
            ],
        ),
    ]
